export enum DATE_FORMATS {
	EU_DATE = "DD.MM.YYYY",
	US_DATE = "MM-DD-YYYY",
	EU_DATETIME = "DD.MM.YYYY, HH:mm",
	US_DATETIME = "MM-DD-YYYY, HH:mm",
	US_DATETIME_AMPM = "MM-DD-YYYY, hh:mm A",
	API_DATE = "YYYY-MM-DD",
	API_DATETIME = "YYYY-MM-DDTHH:mm:ss"
}
